name: Publish image

on:
  release:
    types: [published]
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: License check source
      run: |-
        cd src
        npm ci
        npx license-checker-rseidelsohn --onlyAllow "AFLv2.1; Apache License, Version 2.0; Apache*; Apache-2.0; Apache 2.0; BSD; BSD*; BSD-2-Clause; BSD-3-Clause; BSD-3-Clause-Clear; CC-BY-3.0; CC-BY-4.0; CC0-1.0; ISC; MIT; MIT*; Public Domain; Python-2.0; UNLICENSED; Unlicense; Unlicensed; WTFPL; (BSD-2-Clause OR MIT OR Apache-2.0); (MIT OR Apache-2.0); (MIT OR CC0-1.0); (Unlicense OR Apache-2.0); WTFPL OR ISC; (WTFPL OR MIT);"
    -
      name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: |
          ghcr.io/${{ github.repository }}
        # For a release v1.2.3, we'll produce the following image tags
        #   v1.2.3
        #   1.2.3
        #   1.2
        #   latest
        # Semver pre-release versions are also supported
        # See also:
        # https://github.com/crazy-max/ghaction-docker-meta/tree/0a412843f87333854fa03a809b74056b64c6f31a#handle-semver-tag
        tag-semver: |
          {{raw}}
          {{version}}
          {{major}}.{{minor}}
        label-custom: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/${{ github.sha }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      if: ${{ github.event_name == 'release' }}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    -
      name: Build
      id: docker_build
      uses: docker/build-push-action@v2.2.1
      with:
        push: false
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
    -
      name: License check
      run: docker run ${{ steps.docker_build.outputs.digest }} npx license-checker-rseidelsohn --onlyAllow "AFLv2.1; Apache License, Version 2.0; Apache*; Apache-2.0; Apache 2.0; BSD; BSD*; BSD-2-Clause; BSD-3-Clause; BSD-3-Clause-Clear; CC-BY-3.0; CC-BY-4.0; CC0-1.0; ISC; MIT; MIT*; Public Domain; Python-2.0; UNLICENSED; Unlicense; Unlicensed; WTFPL; (BSD-2-Clause OR MIT OR Apache-2.0); (MIT OR Apache-2.0); (MIT OR CC0-1.0); (Unlicense OR Apache-2.0); WTFPL OR ISC; (WTFPL OR MIT);"
    -
      name: Push
      uses: docker/build-push-action@v2.2.1
      with:
        push: ${{ github.event_name == 'release' }}
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
